### PR TITLE
Add missing dependency

### PR DESCRIPTION
**Pull request by marionleborgne**

### CODE REVIEW

**Comment by fujifish** [comment]
May I ask why this is a missing dependency? 
I haven't had any trouble building and running with out it

**Comment by marionleborgne** [comment]
The app crashes at runtime and throws an an error [1] complaining about this dependency. After adding this dependency and building again, it works fine. 


[1] 
screen shot 2017-06-14 at 3 10 29 pm

**Comment by fujifish** [comment]
Thanks! apparently I manually installed this module and forgot to add it as a dependency

**Comment by marionleborgne** [comment]
You're welcome. Nice app 👍

**Pull request merged**
